const swaggerAutogen = require('swagger-autogen')();
const outputFile ="../Swagger/swagger-output.json"; 
const endpointsFiles = [
  '../AdminRoutes/AdminRoute',
  '../AdminRoutes/OrganizationType.router',
  '../AdminRoutes/Organizations.router',
  '../AdminRoutes/ReportUser/Reports',
  '../AdminRoutes/User.router',

  '../userRoutes/DashBoard.router',
  '../userRoutes/Dentist/Dentist.router',
  '../userRoutes/Labrotory/lab.router',
  '../userRoutes/Notification.router',
  '../userRoutes/Profile.router',
  '../userRoutes/auth/authRouter'
];

const doc = {
  info: {
    title: 'My API',
    description: 'API documentation generated by swagger-autogen',
    version: '1.0.0',
  },
  host: ['https://platix-server.vercel.app/',"http://localhost:5001"], // Modify as needed
  basePath: '/',
  schemes: ['http'],
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    console.log("✅ Swagger JSON generated successfully!");
    process.exit(0); // Ensure the script exits properly
  }).catch((error) => {
    console.error("❌ Swagger generation failed:", error);
    process.exit(1);
  });
